version: '3.7'

networks:
  vsd24-network:
    driver: bridge

services: 
  vsd24-database:
    image: postgres:16
    container_name: vsd24-database
    ports:
      - 5432:5432
    networks:
      - vsd24-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 15s
    volumes: 
      - ./var/pgdata:/var/lib/postgresql/data